Repository MicrosoftDocs/powerbi-docs, pull requests merged in 2023-12, with the labels that each got.

#4897 Update dataflows-premium-features.md to remove statement about not being available within the DOD
  powerbi-docs/transform-model/dataflows/dataflows-premium-features.md
Labels: do-not-merge, aq-pr-triaged

#4905 Update desktop-composite-models.md
  powerbi-docs/transform-model/desktop-composite-models.md
Labels: aq-pr-triaged, assigned-to-contributors

#4912 Update service-dataset-external-org-share-about.md
  powerbi-docs/collaborate-share/service-dataset-external-org-share-about.md
Labels: aq-pr-triaged, assigned-to-contributors

#4917 Update fabric-adoption-roadmap-data-culture.md
  powerbi-docs/guidance/fabric-adoption-roadmap-data-culture.md
Labels: assigned-to-contributors

#4904 Change the Dataset to Semantic Model
  powerbi-docs/developer/embedded/push-datasets-limitations.md
Labels: aq-pr-triaged, assigned-to-contributors
