Repository MicrosoftDocs/powerbi-docs, pull requests merged in 2024-07, with the labels that each got.

#5118 Update service-template-apps-create.md
  powerbi-docs/connect-data/service-template-apps-create.md
Labels: do-not-merge, aq-pr-triaged, assigned-to-contributors

#5120 Update powerbi-implementation-planning-auditing-monitoring-tenant-lev…
  powerbi-docs/guidance/powerbi-implementation-planning-auditing-monitoring-tenant-level-auditing.md
Labels: assigned-to-contributors

#5121 Update interactivity utils docs
  powerbi-docs/developer/visuals/bookmarks-support.md
  powerbi-docs/developer/visuals/create-bar-chart.md
  powerbi-docs/developer/visuals/selection-api.md
  powerbi-docs/developer/visuals/utils-chart.md
  powerbi-docs/developer/visuals/utils-interactivity-selections.md
Labels: do-not-merge, Change sent to author, aq-pr-triaged, powerbi-custom-visuals/subsvc, assigned-to-contributors

#5124 Fix broken link
  powerbi-docs/developer/visuals/bookmarks-support.md
Labels: assigned-to-contributors

#5122 Update desktop-report-lifecycle-datasets.md
  powerbi-docs/connect-data/desktop-report-lifecycle-datasets.md
Labels: do-not-merge, Change sent to author, aq-pr-triaged, pbi-data-sources/subsvc, assigned-to-contributors
