Repository MicrosoftDocs/powerbi-docs, pull requests merged in 2024-06, with the labels that each got.

#5114 Update dataview-mappings.md
  powerbi-docs/developer/visuals/dataview-mappings.md
Labels: assigned-to-contributors

#5113 Update dataview-mappings.md
  powerbi-docs/developer/visuals/dataview-mappings.md
Labels: assigned-to-contributors

#5115 Update service-premium-large-models.md
  powerbi-docs/enterprise/service-premium-large-models.md
Labels: aq-pr-triaged, assigned-to-contributors

#5116 Update explore-data-service.md
  powerbi-docs/consumer/explore-data-service.md
Labels: do-not-merge, aq-pr-triaged, assigned-to-contributors
