Repository MicrosoftDocs/powerbi-docs, pull requests merged in 2024-01, with the labels that each got.

#4936 Update powerbi-implementation-planning-usage-scenario-embed-for-your-…
  powerbi-docs/guidance/powerbi-implementation-planning-usage-scenario-embed-for-your-customers.md
Labels: Change sent to author, powerbi/svc, aq-pr-triaged, powerbi-resource/subsvc

#4930 Update service-connect-excel-power-bi-datasets.md
  powerbi-docs/collaborate-share/service-connect-excel-power-bi-datasets.md
Labels: aq-pr-triaged

#4967 Fix typo in subtitle
  powerbi-docs/developer/embedded/datasets-permissions.md
Labels: assigned-to-contributors

#4962 Update service-premium-service-tags.md
  powerbi-docs/enterprise/service-premium-service-tags.md
Labels: aq-pr-triaged, assigned-to-contributors

#4959 Update projects-overview.md
  powerbi-docs/developer/projects/projects-overview.md
Labels: do-not-merge, Change sent to author, aq-pr-triaged
